// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ammnbpmlflnszknecxye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbW5icG1sZmxuc3prbmVjeHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTY3NTAsImV4cCI6MjA1ODA5Mjc1MH0.aPSVhsb_IRo0PLTpB95t-HQeZi11VOGiFJPqxLuhACo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);